version: '3.9'
services:
  windows:
    image: dockurr/windows:latest
    container_name: windows
    restart: always
    ports:
      - ${HTTP_PORT}:8006
      - ${RDP_PORT}:3389/tcp
      - ${RDP_PORT}:3389/udp
    networks:
      - default
    volumes:
      - data:/var/data
    environment:
      VERSION: "11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      LANGUAGE: "English"
      REGION: "en-US"
      KEYBOARD: "en-US"
    devices:
      - /dev/kvm
    stop_grace_period: 2m

networks:
  default:
    name: docker_windows_network
    driver: bridge

volumes:
  data:
    name: docker_windows_data
    driver: local
