version: '3.9'
services:
  windows:
    image: dockurr/windows:latest
    container_name: windows
    restart: always
    ports:
      - ${HTTP_PORT}:8006
      - ${RDP_PORT}:3389/tcp
      - ${RDP_PORT}:3389/udp
    networks:
      - default
    volumes:
      - data:/var/data
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
    stop_grace_period: 2m

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
